monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-Yamaha_Corporation_MG-XU-00.iec958-stereo"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 9999
        priority.session = 9999
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_input.usb-Yamaha_Corporation_MG-XU-00.iec958-stereo"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 9999
        priority.session = 9999
      }
    }
  }
]
