Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Style/EmptyLambdaParameter:
  Enabled: false
Style/Lambda:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Style/RedundantSelfAssignment:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
