-- Bash Language Server Configuration
-- Installation (Priority Order):
--   1. System (Recommended): sudo pacman -S bash-language-server
--
-- Installed via: pacman
-- Command used: bash-language-server start
-- Strategy: System-only (no project-specific versions needed)
--
-- Provides LSP for shell scripts:
-- - Bash (.sh, .bash)
-- - Shell completion
-- - Syntax checking
-- - Hover documentation

-- No custom configuration needed - using defaults
-- Enabled via init.lua with: vim.lsp.enable("bashls")
