-- TypeScript/JavaScript Language Server Configuration
-- Installation (Priority Order):
--   1. System (Recommended): sudo pacman -S typescript-language-server
--   2. Global via npm: npm install -g typescript-language-server
--
-- Installed via: pacman
-- Command used: typescript-language-server --stdio
-- Strategy: System-only (LSP server)
--
-- Provides LSP for:
-- - TypeScript (.ts, .tsx)
-- - JavaScript (.js, .jsx)
--
-- Note: TypeScript compiler can be installed separately if needed:
--   - System: sudo pacman -S typescript
--   - Global: npm install -g typescript (via asdf nodejs)
--   - Per-project: Already in node_modules (most common)
--
-- Note: For Svelte projects, also enable svelte LSP for .svelte files
-- Note: Uses ts_ls (modern name, formerly tsserver)

-- No custom configuration needed - using defaults
-- Enabled via init.lua with: vim.lsp.enable("ts_ls")
